### ISSUE TITLE
"Tageseinsatz" -> "Kontrollturmdienst"

### ISSUE THREAD

**Issue by will-code-for-food-and-water** [wwi16ama/frontend#101]
![image](https://user-images.githubusercontent.com/29337229/56955513-f17c1d00-6b41-11e9-94b4-d703868f9397.png)

**Comment by JulianKrechel** [comment]
![image](https://user-images.githubusercontent.com/43129043/57178118-48e4fa80-6e6c-11e9-99fe-8efbdb5fd1ac.png)
