### ISSUE TITLE
logbucheintrag hinzufügen Datum

### ISSUE THREAD

**Issue by buzzdee22** [wwi16ama/frontend#106]
![image](https://user-images.githubusercontent.com/50152135/56985693-35464500-6b89-11e9-92a1-ef7e84e05fbf.png)

Wenn ich manuell das Datum eintippe (genau so wie es oben steht wenn es im Kalender ausgewählt wurde), kommt der Fehler.

**Comment by buzzdee22** [comment]
das Problem mit dem manuellen Eintragen des Datums besteht vermutlich überall.

**Comment by simon10419** [comment]
Einfachste Lösung wäre die manuelle Eingabe zu deaktivieren und das Datum nur über den Picker auszuwählen. Wäre das in Ordnung?

**Comment by buzzdee22** [comment]
> Einfachste Lösung wäre die manuelle Eingabe zu deaktivieren und das Datum nur über den Picker auszuwählen. Wäre das in Ordnung?

ja das passt
