### ISSUE TITLE
! Vereinskonto - Finanzen verwalten

### ISSUE THREAD

**Issue by buzzdee22** [wwi16ama/frontend#108]
Ich kann dem Vereinskonto manuell kein Geld hinzufügen/ abbuchen (external transaction)

Das ist dramatisch!

**Comment by buzzdee22** [comment]
siehe 02.010F Finanzverwalter - Kontoverwaltung

**Comment by Yann1c** [comment]
@PiaR11 kann das deinen Task betreffen?

**Comment by PiaR11** [comment]
> @PiaR11 kann das deinen Task betreffen?

Eigentlich nicht... aber ich mache es mit Adrian zusammen. Dafür müssen noch Änderungen im Backend vorgenommen werden
