### ISSUE TITLE
Mitgliederliste - Ansicht

### ISSUE THREAD

**Issue by buzzdee22** [wwi16ama/frontend#109]
Als normaler User sollte ich diesen Ausschnitt von anderen Mitlgliedern nicht sehen können:
![image](https://user-images.githubusercontent.com/50152135/56987800-b81dce80-6b8e-11e9-929e-c2c050e1e10c.png)

Nur als Vorstand, Admin und Finanzverwalter.

**Comment by simon10419** [comment]
Bitte genaueren Screenshot

**Comment by buzzdee22** [comment]
wenn ich in der Mitgliedsliste auf einen Namen klicke:
![image](https://user-images.githubusercontent.com/50152135/57015305-7d5e7980-6c14-11e9-8ec3-40727217ce7e.png)

**Comment by simon10419** [comment]
Kann den Fehler leider nicht reproduzieren. Als eingeloggtes aktives Mitglied kann ich nur meine eigenen Daten sehen. Ich schaus mir aber nochmal genauer an

**Comment by buzzdee22** [comment]
ahhhhh my bad, der account mit dem ich getestet habe war zwar passiv, aber er war kassierer. Sorry
