### ISSUE TITLE
MitgliedskontoNr fälschlicherweise  "required"

### ISSUE THREAD

**Issue by will-code-for-food-and-water** [wwi16ama/frontend#12]
In der Validierung des Frontends wird die Mitgliedskontonummer als erfoderlich betrachtet, laut API-Spec ist sie dies jedoch nicht.

![grafik](https://user-images.githubusercontent.com/29337229/46835444-7a9e5300-cdae-11e8-8bbf-b9e44265985a.png)

![grafik](https://user-images.githubusercontent.com/29337229/46835584-e8e31580-cdae-11e8-925e-961195f8b695.png)

**Comment by simon10419** [comment]
Unsere Info von PO war, dass alle Felder bis auf Ämter und Flugberechtigungen erforderlich sein müssen. Was stimmt jetzt?

**Comment by will-code-for-food-and-water** [comment]
Ich frag mal den PO. Unsere Story hierzu is net Glasklar, aber bei uns steht:

_Die folgenden Felder sind keine Pflichtfelder: Kundenkontonummer, Ämter, Flugberechtigungen_

Aber außerhalb davon: das ganze is ja auch in der **API-Spec** niedergeschrieben, dort sollten ja im Zweifelsfall so Missverständnisse auffallen..

**Comment by will-code-for-food-and-water** [comment]
**PO** sagt das is _kein_ Pflichtfeld.
