### ISSUE TITLE
Datumsprüfung Pilotlog

### ISSUE THREAD

**Issue by will-code-for-food-and-water** [wwi16ama/frontend#81]
Es wird nicht auf folgende Fehler geprüft. Wenn der 400er vom Backend kommt, wird wird nur _"Pflichtfelder nicht ausgefüllt"_ angezeigt.

> This PilotLogEntry has an invalid Departure Time: 2019-04-23T12:00. The Departure Time has to be earlier than today. 

> This PilotLogEntry has an invalid Departure Time: 2019-04-08T12:00. The Depature Time has to be earlier than the Arrival Time (2019-04-04T12:00).

**Comment by simon10419** [comment]
Solved siehe PR
