### ISSUE TITLE
Aufwandsliste / Aufwände Eintragen

### ISSUE THREAD

**Issue by will-code-for-food-and-water** [wwi16ama/frontend#90]
![image](https://user-images.githubusercontent.com/29337229/56800820-3c352680-681c-11e9-9711-94e24d9d1cef.png)
Wenn ich auf hinzufügen klicke, passiert nichts.

Der Fehler tritt auf dem Integrationsserver und Lokal auf.

**Comment by simon10419** [comment]
Ist aktuell in Bearbeitung, Story wurde vorher gerissen
