### ISSUE TITLE
komische Schrift Aufwandsliste

### ISSUE THREAD

**Issue by will-code-for-food-and-water** [wwi16ama/frontend#93]
![image](https://user-images.githubusercontent.com/29337229/56821938-eaa68f00-684f-11e9-87cd-3c99ecafce34.png)

**Comment by simon10419** [comment]
![image](https://user-images.githubusercontent.com/25517648/56855642-e1e6b380-694a-11e9-84ce-5f0fd41c2607.png)

**Comment by simon10419** [comment]
Besser?
