### ISSUE TITLE
Prüfung Planelog

### ISSUE THREAD

**Issue by will-code-for-food-and-water** [wwi16ama/frontend#95]
![image](https://user-images.githubusercontent.com/29337229/56855357-fd9b8b00-6945-11e9-8a85-1a2ce109930c.png)

#88 immernoch. Der Fehler war nicht das Vorzeichen, sondern dass ihr Strings und nicht Zahlen verglichen habt. Dadurch ist `"90"` tatsächlich größer als `"110"`..

**Comment by simon10419** [comment]
@Nisatru FYI
