### ISSUE TITLE
Aufwände für einen Tag mit Wert 0?

### ISSUE THREAD

**Issue by simon10419** [wwi16ama/frontend#97]
![image](https://user-images.githubusercontent.com/25517648/56855785-b913ed80-694d-11e9-9f1a-68c7ba45eb7f.png)

**Comment by simon10419** [comment]
Backend weiß Bescheid

**Comment by JulianKrechel** [comment]
Wird im Backend falsch berechnet...

**Comment by will-code-for-food-and-water** [comment]
Is im Backend gefixt, ihr könnt den Issue schließen

**Comment by simon10419** [comment]
Musik in meinen Ohren, danke!
